version: "3.8"

services:

  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - "80:80"
    deploy:
      replicas: 2
    networks:
      - front

  redis:
    image: redis:3.2
    deploy:
      replicas: 1
    networks:
      - front

  worker:
    image: bretfisher/examplevotingapp_worker:java
    networks:
      - front
      - back
    deploy:
      replicas: 1

  db:
    image: postgres:9.4
    volumes:
      - type: volume
        source: psql-data
        target: /var/lib/postgresql/data
    networks:
      - back
    deploy:
      replicas: 1
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - "8082:80"
    networks:
      - back
    deploy:
      replicas: 1



volumes:
  psql-data:

networks:
  front:
    driver: overlay
  back: 
    driver: overlay
